on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "Preparing '${{ github.event.ref }}' for release"
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      # Force upgrading pip (Might be removed at some point)
      - run: pip install --upgrade pip
      - run: pip install -r requirements.txt
      - uses: actions/download-artifact@v4
        with:
          name: updated-version-data
          path: RandomizerCore
      - run: mkdir build
      - run: python setup.py build
      - run: python build.py
      - uses: actions/upload-artifact@v4
        with:
          name: release-build-${{ matrix.os }}
          path: build/*.zip
